# Practice 1

In [6]:
[item**2 for item in [1, 2, 3, 4, 5]]

[1, 4, 9, 16, 25]

In [7]:
"""
TEMP
"""
print("asd")


asd


In [8]:
"""
What is 7 to the power of 4?
"""
print(7**4)

2401


In [15]:
"""
"Split this string." into a list.
"""
s = "Split this string."
print(s.split())

['Split', 'this', 'string.']


In [16]:
"""
The diameter of Earth is 12742 kilometers
"""
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers".format(planet, diameter))

The diameter of Earth is 12742 kilometers


In [26]:
"""
"Given the nested list, grab the word "hello""
"""
l = [1, 2, [3, 4], [5, [100, 200, ['hello']], 23, 11], 1, 7]
print(l[3][1][2])

['hello']


In [36]:
"""
"Given the nested dictionary, grab the word "hello""
"""
d = {'k1':[1, 2, 3, {'tricky': ['oh', 'man', 'inception', {'target':[1, 2, 3, 'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


In [38]:
def domainGet(email):
    return email.split("@")[1]

print(domainGet("example@gmail.com"))


gmail.com


In [45]:
def findDog(sentence):
    return 'dog' in sentence.lower().split(" ")

print(findDog('Is there a dog here?'))
print(findDog('Is there a DOG here?'))
print(findDog('Is there a cat here?'))

True
True
False


In [50]:
def countDog(string):
    return sum(map(lambda x : (x == "dog") == 1, string.split())) 

print(countDog("Is there dog dog a dog here?"))

3


In [1]:
#def filterS(string):
#    return list(filter(lambda item : item[0] != 's', string.split()))

#print(filterS("Is there dog dog a dog sphere?"))

# PRACTICE 2.
## Numpy

In [5]:
import numpy as np
my_list = [1, 2, 3]
np.array(my_list)


array([1, 2, 3])

In [23]:
np.zeros(10)
np.ones(10)
arr = np.arange(10)
arr[0:10] = 5
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [25]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [26]:
arr = np.arange(10, 50, 2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [32]:
arr = np.arange(0, 9)
arr.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
arr = np.random.rand(1)
arr

array([0.13408861])

In [46]:
arr = np.random.standard_normal(25)
arr

array([-0.2941093 , -0.60526119,  1.14164121, -0.68008429, -0.14339784,
       -0.71276438,  0.26713257,  0.84310817,  0.7334892 , -1.44124097,
       -0.3919113 ,  0.63020248, -0.99955554, -0.41336715,  0.18181837,
        1.60397931,  0.08647484, -0.80741295, -0.22483036,  0.09640085,
       -0.02418039,  0.90418191, -0.55755145,  1.26064285, -0.70393758])

In [61]:
arr = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [67]:
arr = np.linspace(0, 1, 20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Given Matrices

In [68]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [105]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [80]:
mat = np.arange(1,26).reshape(5,5)
mat[3,4]

20

In [79]:
mat = np.arange(2, 13, 5).reshape(3, 1)
mat

array([[ 2],
       [ 7],
       [12]])

In [81]:
mat = np.arange(1,26).reshape(5,5)
mat[4]

array([21, 22, 23, 24, 25])

In [89]:
mat = np.arange(1,26).reshape(5,5)
mat[1:][2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [104]:
mat = np.arange(1,26).reshape(5,5)
mat.sum()
mat.std()

7.211102550927978

In [110]:
# Sum of columns
mat.sum(axis=0)

array([55, 60, 65, 70, 75])